//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympiadsEntities1 : DbContext
    {
        private static OlympiadsEntities1 _context;
        public OlympiadsEntities1()
            : base("name=OlympiadsEntities1")
        {
        }

        public static OlympiadsEntities1 GetContext()
        {
            if (_context == null)
                _context = new OlympiadsEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OlympiadParticipants> OlympiadParticipants { get; set; }
        public virtual DbSet<Olympiads> Olympiads { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Schools> Schools { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
