//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int TaskID { get; set; }
        public Nullable<int> OlympiadID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string TaskDescription { get; set; }
    
        public virtual Olympiads Olympiads { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
